"""initial

Revision ID: 85ada5550a7f
Revises: 
Create Date: 2026-06-09 10:37:59.269886

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '85ada5550a7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('doenca', sa.String(), nullable=False),
    sa.Column('confianca', sa.Float(), nullable=False),
    sa.Column('area_percentual', sa.Float(), nullable=False),
    sa.Column('severidade', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    op.drop_table('scan_sessions')
    # ### end Alembic commands ###
