"""add nivel_confianca

Revision ID: fa121cd771e5
Revises: 85ada5550a7f
Create Date: 2026-06-09 11:09:12.497765

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fa121cd771e5'
down_revision: Union[str, None] = '85ada5550a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('detections', sa.Column('nivel_confianca', sa.String(), nullable=True))
    op.execute("UPDATE detections SET nivel_confianca = 'boa' WHERE nivel_confianca IS NULL")
    op.alter_column('detections', 'nivel_confianca', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'nivel_confianca')
    # ### end Alembic commands ###
